# Generated by Django 3.2.8 on 2021-10-13 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Community_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True, verbose_name='Título')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('r_social1', models.CharField(blank=True, max_length=200, null=True, verbose_name='Facebook')),
                ('r_social2', models.CharField(blank=True, max_length=200, null=True, verbose_name='Instagram')),
                ('r_social3', models.CharField(blank=True, max_length=200, null=True, verbose_name='Linkedin')),
                ('r_social4', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram')),
                ('r_social5', models.CharField(blank=True, max_length=200, null=True, verbose_name='Twitter')),
            ],
            options={
                'verbose_name': 'Community_info',
                'verbose_name_plural': 'Community_infos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Link_Enlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp', models.CharField(blank=True, max_length=200, null=True, verbose_name='Whatsapp')),
                ('telegram', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram')),
                ('discord', models.CharField(blank=True, max_length=200, null=True, verbose_name='Discord')),
            ],
            options={
                'verbose_name': 'Link_Enlace',
                'verbose_name_plural': 'Links_Enlaces',
                'ordering': ['id'],
            },
        ),
    ]
