# Generated by Django 3.2.8 on 2021-12-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_ingleslink'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250, unique=True, verbose_name='API url')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='API name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='API description')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='API image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
