# Generated by Django 3.2.8 on 2022-01-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_apilink'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=250, unique=True, verbose_name='Editor url')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Editor name')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Editor description')),
                ('image', models.CharField(blank=True, max_length=200, null=True, verbose_name='Editor image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
